import os
DEBUG = True
DIRNAME = os.path.dirname(__file__)
SERVERNAME = 'http://localhost:8888'
STATIC_PATH = os.path.join(DIRNAME, 'static')
TEMPLATE_PATH = os.path.join(DIRNAME, 'template')
DATE_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'
TEMPLATE_PATH = os.path.join(DIRNAME, 'template')
COOKIE_SECRET = '12345678'
ADMIN_EMAILS = ['nikhil@tinktime.com']
DEBUG_LOG = 'feeder.log'
SUBSCRIBER_FILE='subscriber_list.txt'
REDIS_SHARDS = [{"server": 'localhost', "port":6379},{"server": 'localhost', "port":6379}]
TWILIO_ACCOUNT_SID="ACb6dbd5fd90ca9916cca28393dd171374"
TWILIO_AUTH_TOKEN="8ef8f04e1c446d947c446186a54ebede"
TWILIO_ACCOUNT_NUMBER="+46769439377"
IOS_CERT_FILE_PATH=os.path.join(DIRNAME,"tinktime-dev.pem")
IOS_KEY_FILE_PATH=os.path.join(DIRNAME,"tinktime-devkey.pem")
ANDROID_API_KEY= 'AIzaSyA3zWzfKgsouxhy4aILaRrAd3GVFKWWhqI'