import os
DEBUG = True
DIRNAME = os.path.dirname(__file__)
SERVERNAME = 'http://localhost:8888'
STATIC_PATH = os.path.join(DIRNAME, 'static')
TEMPLATE_PATH = os.path.join(DIRNAME, 'template')
DATE_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'
TEMPLATE_PATH = os.path.join(DIRNAME, 'template')
COOKIE_SECRET = '12345678'
ADMIN_EMAILS = ['nikhil@tinktime.com']
DEBUG_LOG = 'feeder.log'
SUBSCRIBER_FILE='subscriber_list.txt'
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_ACCOUNT_NUMBER="+"
IOS_CERT_FILE_PATH=os.path.join(DIRNAME,"tinktime-dev.pem")
IOS_KEY_FILE_PATH=os.path.join(DIRNAME,"tinktime-devkey.pem")
ANDROID_API_KEY= ''
TRINKET_IMG_DIR='/static/trinkets/img/'
TRINKET_SWIFFY_DIR='/static/trinkets/html/'
GOOGLE_CLIENT_ID = '-.apps.googleusercontent.com'
GOOGLE_SECRET = ''
ANALYTICS_TEAM = ['monica@tinktime','fredrik@tinktime.com']
GOOGLE_AUTH_REDIRECT_URI ="http://localhost:8888/auth"
PROFILE_IMG_DIR = '/static/img/user_profile/'
USE_CDN_SWITCH = 1
AWSAccessKeyId=''
AWSSecretKey='/'
S3_BUCKET_TRINKET_IMG = 'tt-trinket-thumbnail'
S3_BUCKET_TRINKET_SWIFFY = 'tt-trinket-swiffy'
S3_BUCKET_TRINKET_USER_PROFILE = 'tt-user-profile-img'
CDN_DOMAIN_NAME_TRINKET_IMG = '.cloudfront.net'
CDN_DOMAIN_NAME_TRINKET_SWIFFY = '.cloudfront.net'
CDN_DOMAIN_NAME_USER_PROFILE = '.cloudfront.net'
REDIS_CLUSTER = {"server": '192.168.10.183', "port":7000}