import os
DEBUG = True
DIRNAME = os.path.dirname(__file__)
SERVERNAME = 'http://localhost:80'
STATIC_PATH = os.path.join(DIRNAME, 'static')
TEMPLATE_PATH = os.path.join(DIRNAME, 'template')
DATE_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'
TEMPLATE_PATH = os.path.join(DIRNAME, 'template')
COOKIE_SECRET = '12345678'
ADMIN_EMAILS = ['nl@tinktime.com']
DEBUG_LOG = 'feeder.log'
SUBSCRIBER_FILE='subscriber_list.txt'
REDIS_SHARDS = [{"server": '192.168.10.111', "port":6379},{"server": '192.168.10.111', "port":6379}]
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_ACCOUNT_NUMBER="+"
IOS_CERT_FILE_PATH=os.path.join(DIRNAME,"tinktime-dev.pem")
IOS_KEY_FILE_PATH=os.path.join(DIRNAME,"tinktime-devkey.pem")
ANDROID_API_KEY= ''
TRINKET_IMG_DIR='/static/trinkets/img/'
TRINKET_SWIFFY_DIR='/static/trinkets/html/'
GOOGLE_CLIENT_ID = ''
GOOGLE_SECRET = ''
ANALYTICS_TEAM = []
GOOGLE_AUTH_REDIRECT_URI ="http://localhost:8888/auth"